Repository geocortex/dev-center, pull requests merged in 2020-04, with the labels that each got.

#6 Fix active link detection for navbar links
  docusaurus.config.js
  yarn.lock
Labels: bug

#8 Add CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#9 Update root page title
  src/pages/index.js
Labels: enhancement

#10 Add some highlighting and cleanup to code blocks
  docs/mobile/change-default-search-behaviour.mdx
  docs/mobile/concepts-advanced-layout.mdx
  docs/mobile/concepts-app-config.mdx
  docs/mobile/concepts-key-concepts.mdx
  docs/mobile/concepts-layout.mdx
  docs/mobile/implement-component-participate-app-config.mdx
Labels: enhancement

#11 Rename behaviour to behavior
  docs/mobile/change-default-behavior.mdx
  docs/mobile/change-default-search-behavior.mdx
  docs/mobile/concepts-app-config.mdx
  docs/mobile/concepts-commands-operations.mdx
  docs/mobile/concepts-components-services.mdx
  docs/mobile/concepts-events.mdx
  docs/mobile/dependency-injection.mdx
  docs/mobile/implement-command-operation.mdx
  docs/mobile/implement-component-participate-app-config.mdx
  docs/mobile/implement-component-with-ui.mdx
  docs/mobile/overview.mdx
  docs/mobile/snippets/designer-callout.mdx
  docs/workflow/concepts-key-concepts.mdx
  docs/workflow/implement-custom-activity-mobile.mdx
  docs/workflow/implement-custom-activity-server.mdx
  docs/workflow/implement-custom-activity-web.mdx
  docs/workflow/snippets/designer-callout.mdx
  sidebars.js
Labels: enhancement

#12 Fix broken localhost link
  docs/mobile/viewmodel-helper-class.mdx
Labels: bug

#18 Update font weight for admonition title
  src/css/custom.css
Labels: enhancement
